spring.datasource.url=jdbc:postgresql://localhost:5432/resale
spring.datasource.username=moderator
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=1111

path.upload=uploads
